[package]
name = "splitscreen-cli"
version = "0.2.0"
edition = "2018"

[dependencies]
clap = { version = "3.1.2", features = ["cargo"] }
font-loader = "0.11.0"
image = "0.23.14"
imageproc = "0.22.0"
rusttype = "0.9.2"
